USE emergency_waitlist;

INSERT INTO user (user_id, username, user_password, email, user_role) VALUES (DEFAULT, 'admin', 'admin', 'admin@admin.com', 'admin');
INSERT INTO user (user_id, username, user_password, email, user_role, arrival_time, severity) VALUES (DEFAULT, 'joe', 'joe', 'joe@patient.com', 'patient', FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(NOW()) + RAND() * 86400), '%Y-%m-%d %H:%i:%s'), FLOOR(RAND() * 5 + 1));
INSERT INTO user (user_id, username, user_password, email, user_role, arrival_time, severity) VALUES (DEFAULT, 'sam', 'sam', 'sam@patient.com', 'patient', FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(NOW()) + RAND() * 86400), '%Y-%m-%d %H:%i:%s'), FLOOR(RAND() * 5 + 1));
INSERT INTO user (user_id, username, user_password, email, user_role, arrival_time, severity) VALUES (DEFAULT, 'max', 'max', 'max@patient.com', 'patient', FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(NOW()) + RAND() * 86400), '%Y-%m-%d %H:%i:%s'), FLOOR(RAND() * 5 + 1));
INSERT INTO user (user_id, username, user_password, email, user_role, arrival_time, severity) VALUES (DEFAULT, 'pho', 'pho', 'pho@patient.com', 'patient', FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(NOW()) + RAND() * 86400), '%Y-%m-%d %H:%i:%s'), FLOOR(RAND() * 5 + 1));
INSERT INTO user (user_id, username, user_password, email, user_role, arrival_time, severity) VALUES (DEFAULT, 'mel', 'mel', 'mel@patient.com', 'patient', FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(NOW()) + RAND() * 86400), '%Y-%m-%d %H:%i:%s'), FLOOR(RAND() * 5 + 1));
INSERT INTO user (user_id, username, user_password, email, user_role, arrival_time, severity) VALUES (DEFAULT, 'jay', 'jay', 'jay@patient.com', 'patient', FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(NOW()) + RAND() * 86400), '%Y-%m-%d %H:%i:%s'), FLOOR(RAND() * 5 + 1));
INSERT INTO user (user_id, username, user_password, email, user_role, arrival_time, severity) VALUES (DEFAULT, 'jon', 'jon', 'jon@patient.com', 'patient', FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(NOW()) + RAND() * 86400), '%Y-%m-%d %H:%i:%s'), FLOOR(RAND() * 5 + 1));
INSERT INTO user (user_id, username, user_password, email, user_role, arrival_time, severity) VALUES (DEFAULT, 'ron', 'ron', 'ron@patient.com', 'patient', FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(NOW()) + RAND() * 86400), '%Y-%m-%d %H:%i:%s'), FLOOR(RAND() * 5 + 1));
INSERT INTO user (user_id, username, user_password, email, user_role, arrival_time, severity) VALUES (DEFAULT, 'don', 'don', 'don@patient.com', 'patient', FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(NOW()) + RAND() * 86400), '%Y-%m-%d %H:%i:%s'), FLOOR(RAND() * 5 + 1));
INSERT INTO user (user_id, username, user_password, email, user_role, arrival_time, severity) VALUES (DEFAULT, 'ray', 'ray', 'ray@patient.com', 'patient', FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(NOW()) + RAND() * 86400), '%Y-%m-%d %H:%i:%s'), FLOOR(RAND() * 5 + 1));
INSERT INTO user (user_id, username, user_password, email, user_role, arrival_time, severity) VALUES (DEFAULT, 'kev', 'kev', 'kev@patient.com', 'patient', FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(NOW()) + RAND() * 86400), '%Y-%m-%d %H:%i:%s'), FLOOR(RAND() * 5 + 1));
INSERT INTO user (user_id, username, user_password, email, user_role, arrival_time, severity) VALUES (DEFAULT, 'zak', 'zak', 'zak@patient.com', 'patient', FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(NOW()) + RAND() * 86400), '%Y-%m-%d %H:%i:%s'), FLOOR(RAND() * 5 + 1));